"""Render a pyinfra inventory file from a list of kresko assets."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from harness.selectors import active_assets


def _group_name(name: str) -> str:
    safe = re.sub(r"\W+", "_", name.strip())
    if not safe or safe[0].isdigit():
        safe = f"group_{safe}"
    return safe


def host_tuple(asset: dict[str, Any], ssh: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    public_ip = asset["public_ip"]
    data = {
        "ssh_user": asset.get("ssh_user") or ssh.get("user", "root"),
        "kresko_name": asset.get("name"),
        "kresko_role": asset.get("role"),
        "kresko_provider": asset.get("provider"),
        "kresko_provider_id": asset.get("provider_id"),
        "kresko_public_ip": public_ip,
        "kresko_private_ip": asset.get("private_ip", ""),
        "kresko_region": asset.get("region", ""),
        "kresko_size": asset.get("size", ""),
        "kresko_experiment": asset.get("experiment", ""),
        "kresko_run": asset.get("run", ""),
    }
    if ssh.get("key_path"):
        data["ssh_key"] = ssh["key_path"]
    return public_ip, data


def pyinfra_groups(
    assets: list[dict[str, Any]], ssh: dict[str, Any]
) -> dict[str, list[tuple[str, dict[str, Any]]]]:
    groups: dict[str, list[tuple[str, dict[str, Any]]]] = {"all": []}
    for asset in active_assets(assets):
        item = host_tuple(asset, ssh)
        groups["all"].append(item)
        for key in (asset.get("role"), asset.get("provider")):
            if key:
                groups.setdefault(_group_name(str(key)), []).append(item)
    return groups


def write_pyinfra_inventory(
    path: str | Path,
    assets: list[dict[str, Any]],
    ssh: dict[str, Any],
) -> Path:
    path = Path(path)
    groups = pyinfra_groups(assets, ssh)
    lines = [
        "# Generated by harness.inventory.write_pyinfra_inventory",
        "# pyinfra inventory file",
        "",
    ]
    for group, hosts in sorted(groups.items()):
        lines.append(f"{_group_name(group)} = {hosts!r}")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
