use anyhow::Result;

use crate::config::{Config, Provider, S3Config, resolve_value};
use crate::zebra_config;

pub fn run(
    chain_id: &str,
    experiment: &str,
    provider: &str,
    ssh_pub_key_path: Option<String>,
    ssh_key_name: Option<String>,
) -> Result<()> {
    let provider: Provider = provider.parse()?;
    let dir = std::path::Path::new(experiment);
    if dir.exists() {
        anyhow::bail!("Experiment directory '{}' already exists", experiment);
    }

    // Create directory structure
    std::fs::create_dir_all(dir.join("payload"))?;
    std::fs::create_dir_all(dir.join("data"))?;
    std::fs::create_dir_all(dir.join("scripts"))?;

    // Write default zebrad.toml template
    std::fs::write(dir.join("zebrad.toml"), zebra_config::DEFAULT_ZEBRAD_TOML)?;

    // Write node_init.sh
    std::fs::write(dir.join("scripts/node_init.sh"), NODE_INIT_SH)?;
    std::fs::write(dir.join("scripts/vars.sh"), VARS_SH_TEMPLATE)?;

    // Create config
    let config = Config {
        validators: Vec::new(),
        chain_id: chain_id.to_string(),
        experiment: experiment.to_string(),
        ssh_pub_key_path: resolve_value(
            ssh_pub_key_path.as_deref(),
            "KRESKO_SSH_PUB_KEY_PATH",
            "~/.ssh/id_rsa.pub",
        ),
        ssh_key_name: resolve_value(
            ssh_key_name.as_deref(),
            "KRESKO_SSH_KEY_NAME",
            &default_ssh_key_name(),
        ),
        ssh_key_path: resolve_value(None, "KRESKO_SSH_KEY_PATH", "~/.ssh/id_rsa"),
        provider,
        do_token: resolve_value(None, "DIGITALOCEAN_TOKEN", ""),
        gcp_project: resolve_value(None, "GOOGLE_CLOUD_PROJECT", ""),
        gcp_key_json_path: resolve_value(None, "GOOGLE_CLOUD_KEY_JSON_PATH", ""),
        s3: S3Config {
            region: resolve_value(None, "AWS_DEFAULT_REGION", "us-east-1"),
            access_key_id: resolve_value(None, "AWS_ACCESS_KEY_ID", ""),
            secret_access_key: resolve_value(None, "AWS_SECRET_ACCESS_KEY", ""),
            bucket_name: resolve_value(None, "AWS_S3_BUCKET", "kresko-data"),
            endpoint: resolve_value(None, "AWS_S3_ENDPOINT", ""),
        },
    };

    config.save(dir)?;

    println!("Initialized experiment '{experiment}' for chain '{chain_id}'");
    println!("  Directory: {}", dir.display());
    println!("  Provider:  {provider}");
    println!();
    println!("Next steps:");
    println!("  1. cd {experiment}");
    println!("  2. kresko add -t validator -c <N>");
    println!("  3. kresko up");

    Ok(())
}

const NODE_INIT_SH: &str = r#"#!/bin/bash
set -euo pipefail

ARCHIVE_NAME="payload.tar.gz"
export DEBIAN_FRONTEND=noninteractive

echo "=== Installing dependencies ==="
apt-get update -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"
apt-get install -y build-essential ufw curl jq chrony tmux btop nethogs

echo "=== Configuring firewall ==="
ufw allow 18233/tcp   # P2P
ufw allow 18232/tcp   # RPC
ufw allow 18233/udp
ufw allow 18232/udp
ufw --force enable || true

echo "=== Configuring time sync ==="
systemctl enable chrony
systemctl start chrony

echo "=== Configuring BBR congestion control ==="
modprobe tcp_bbr || true
sysctl -w net.core.default_qdisc=fq
sysctl -w net.ipv4.tcp_congestion_control=bbr
echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf

echo "=== Extracting payload ==="
tar -xzf /root/$ARCHIVE_NAME -C /root/
source /root/payload/vars.sh

cd $HOME
hostname=$(hostname)
parsed_hostname=$(echo $hostname | awk -F'-' '{print $1 "-" $2}')

echo "=== Installing binaries ==="
cp payload/build/zebrad /usr/local/bin/zebrad
chmod +x /usr/local/bin/zebrad

if [ -f payload/build/kresko ]; then
    cp payload/build/kresko /usr/local/bin/kresko
    chmod +x /usr/local/bin/kresko
fi

echo "=== Setting up zebra config ==="
mkdir -p /root/.cache/zebra
mkdir -p /root/.config
cp payload/$parsed_hostname/zebrad.toml /root/.config/zebrad.toml

echo "=== Node: $parsed_hostname ==="
echo "=== Starting zebrad ==="

LOG_FILE="/root/logs"
zebrad -c /root/.config/zebrad.toml start 2>&1 | tee -a "$LOG_FILE"
"#;

fn default_ssh_key_name() -> String {
    std::env::var("USER")
        .or_else(|_| std::env::var("USERNAME"))
        .unwrap_or_default()
}

const VARS_SH_TEMPLATE: &str = r#"#!/bin/bash
# Environment variables for kresko nodes
# This file is generated by kresko genesis

export CHAIN_ID=""
export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
export AWS_DEFAULT_REGION=""
export AWS_S3_BUCKET=""
export AWS_S3_ENDPOINT=""
"#;
