use anyhow::Result;

use crate::config::{Config, Provider, resolve_value};
use crate::zebra_config;

pub fn run(
    chain_id: &str,
    experiment: &str,
    provider: &str,
    ssh_pub_key_path: Option<String>,
    ssh_key_name: Option<String>,
) -> Result<()> {
    let provider: Provider = provider.parse()?;
    let dir = std::path::Path::new(experiment);
    if dir.exists() {
        anyhow::bail!("Experiment directory '{}' already exists", experiment);
    }

    // Create directory structure
    std::fs::create_dir_all(dir.join("payload"))?;
    std::fs::create_dir_all(dir.join("data"))?;
    std::fs::create_dir_all(dir.join("scripts"))?;

    // Write default zebrad.toml template
    std::fs::write(dir.join("zebrad.toml"), zebra_config::DEFAULT_ZEBRAD_TOML)?;

    // Write node_init.sh
    std::fs::write(dir.join("scripts/node_init.sh"), NODE_INIT_SH)?;
    std::fs::write(dir.join("scripts/vars.sh"), VARS_SH_TEMPLATE)?;

    let ssh_key_name_val = resolve_value(
        ssh_key_name.as_deref(),
        "KRESKO_SSH_KEY_NAME",
        &default_ssh_key_name(),
    );
    let ssh_pub_key_path_val = resolve_value(
        ssh_pub_key_path.as_deref(),
        "KRESKO_SSH_PUB_KEY_PATH",
        "~/.ssh/id_rsa.pub",
    );
    let ssh_key_path_val = resolve_value(None, "KRESKO_SSH_KEY_PATH", "~/.ssh/id_rsa");

    // Create config
    let config = Config {
        miners: Vec::new(),
        chain_id: chain_id.to_string(),
        experiment: experiment.to_string(),
        ssh_pub_key_path: ssh_pub_key_path_val.clone(),
        ssh_key_name: ssh_key_name_val.clone(),
        ssh_key_path: ssh_key_path_val.clone(),
        provider,
        local_genesis: None,
    };

    config.save(dir)?;

    // Write .env with provider-specific template, pre-filling known values
    write_env(
        dir,
        provider,
        &ssh_key_name_val,
        &ssh_pub_key_path_val,
        &ssh_key_path_val,
    )?;

    println!("Initialized experiment '{experiment}' for chain '{chain_id}'");
    println!("  Directory: {}", dir.display());
    println!("  Provider:  {provider}");
    println!("  .env:      {}/.env (fill in credentials)", dir.display());
    println!();
    println!("Next steps:");
    println!("  1. cd {experiment}");
    println!("  2. Edit .env and fill in your credentials");
    println!("  3. kresko add -t miner -c <N>");
    println!("  4. kresko up");

    Ok(())
}

/// Read an env var, returning its value or a fallback default.
fn env_or(var: &str, default: &str) -> String {
    std::env::var(var).unwrap_or_else(|_| default.to_string())
}

fn write_env(
    dir: &std::path::Path,
    provider: Provider,
    ssh_key_name: &str,
    ssh_pub_key_path: &str,
    ssh_key_path: &str,
) -> Result<()> {
    let aws_access_key = env_or("AWS_ACCESS_KEY_ID", "");
    let aws_secret_key = env_or("AWS_SECRET_ACCESS_KEY", "");
    let aws_bucket = env_or("AWS_S3_BUCKET", "kresko-data");

    let env_content = match provider {
        Provider::DigitalOcean => {
            let do_token = env_or("DIGITALOCEAN_TOKEN", "");
            let aws_region = env_or("AWS_DEFAULT_REGION", "nyc3");
            let aws_endpoint = env_or("AWS_S3_ENDPOINT", "https://nyc3.digitaloceanspaces.com");
            format!(
                r#"# DigitalOcean Configuration
DIGITALOCEAN_TOKEN={do_token}

# SSH Configuration
KRESKO_SSH_KEY_NAME={ssh_key_name}
KRESKO_SSH_PUB_KEY_PATH={ssh_pub_key_path}
KRESKO_SSH_KEY_PATH={ssh_key_path}

# S3 Configuration (DigitalOcean Spaces or AWS S3)
AWS_ACCESS_KEY_ID={aws_access_key}
AWS_SECRET_ACCESS_KEY={aws_secret_key}
AWS_DEFAULT_REGION={aws_region}
AWS_S3_BUCKET={aws_bucket}
AWS_S3_ENDPOINT={aws_endpoint}
"#
            )
        }
        Provider::GoogleCloud => {
            let gcp_project = env_or("GOOGLE_CLOUD_PROJECT", "");
            let gcp_key_path = env_or("GOOGLE_CLOUD_KEY_JSON_PATH", "");
            let aws_region = env_or("AWS_DEFAULT_REGION", "us-east-1");
            let aws_endpoint = env_or("AWS_S3_ENDPOINT", "");
            format!(
                r#"# Google Cloud Configuration
GOOGLE_CLOUD_PROJECT={gcp_project}
GOOGLE_CLOUD_KEY_JSON_PATH={gcp_key_path}

# SSH Configuration
KRESKO_SSH_KEY_NAME={ssh_key_name}
KRESKO_SSH_PUB_KEY_PATH={ssh_pub_key_path}
KRESKO_SSH_KEY_PATH={ssh_key_path}

# S3 Configuration (GCS or AWS S3)
AWS_ACCESS_KEY_ID={aws_access_key}
AWS_SECRET_ACCESS_KEY={aws_secret_key}
AWS_DEFAULT_REGION={aws_region}
AWS_S3_BUCKET={aws_bucket}
AWS_S3_ENDPOINT={aws_endpoint}
"#
            )
        }
    };

    std::fs::write(dir.join(".env"), env_content)?;
    Ok(())
}

const NODE_INIT_SH: &str = include_str!("../../scripts/node_init.sh");

fn default_ssh_key_name() -> String {
    std::env::var("USER")
        .or_else(|_| std::env::var("USERNAME"))
        .unwrap_or_default()
}

const VARS_SH_TEMPLATE: &str = r#"#!/bin/bash
# Environment variables for kresko nodes
# This file is generated by kresko genesis

export CHAIN_ID=""
export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
export AWS_DEFAULT_REGION=""
export AWS_S3_BUCKET=""
export AWS_S3_ENDPOINT=""
"#;
