#!/bin/bash
# Environment variables for kresko nodes
# This file is generated by kresko genesis

export CHAIN_ID=""
export AWS_ACCESS_KEY_ID=""
export AWS_SECRET_ACCESS_KEY=""
export AWS_DEFAULT_REGION=""
export AWS_S3_BUCKET=""
export AWS_S3_ENDPOINT=""
